services:
  todo_backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgres
  
  postgres:
    image: postgres:15
    container_name: postgres_todo
    environment:
      POSTGRES_DB: todo
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local